### PR TITLE
Add Dockerfile

### LINKED ISSUE #11: Add Dockerfile
This will make compy easier for non-programmers to use.

### PR DESCRIPTION
**Pull request by andrewgaul**
Fixes #11.

### CODE REVIEW

**Comment by andrewgaul** [comment]
@kahing Please review.

**Comment by kahing** [comment]
how about printing a couple lines on how to import the cert to the browser?

**Comment by andrewgaul** [comment]
Opened #24 to track importing certificates.

**Comment by RReverser** [comment]
@gaul How did you build it? Image at https://hub.docker.com/r/andrewgaul/compy/ seems somewhat outdated, and during manual build it fails with `COPY failed: stat /var/lib/docker/tmp/docker-builder800255693/compy: no such file or directory`.

**Comment by gaul** [comment]
Previously the Dockerfile assumed that one had already built compy outside the image.  Please review #33 which builds compy as part of building the Docker image.

**Pull request merged**
